/* AUTO-GENERATED BY config_gen.py */
#include "ptl.h"
#include "ptl_trace.h"
#include "uart.h"
#include "burner.h"


/* --- JOB FUNCTIONS --- */

void Job_TASK1(void *p) {
    (void)p;
    UART_printf("[TASK1] Start (Run: 10ms)\n");
    Burn(10);
    UART_printf("[TASK1] End\n");
}

void Job_TASK2(void *p) {
    (void)p;
    UART_printf("[TASK2] Start (Run: 20ms)\n");
    Burn(20);
    UART_printf("[TASK2] End\n");
}

/* --- CONFIGURATION --- */
int main(void) {
    UART_init();
    UART_printf("\n=== AUTO-GENERATED CONFIGURATION ===\n");
    UART_printf("Global Policy: PTL_POLICY_SKIP\n");

    static PTL_TaskConfig_t t[] = {
        /* TASK1: PTL_POLICY_USE_GLOBAL */
        { "TASK1", pdMS_TO_TICKS(50), pdMS_TO_TICKS(50), 2, 256, Job_TASK1, NULL, PTL_POLICY_USE_GLOBAL },
        /* TASK2: PTL_POLICY_USE_GLOBAL */
        { "TASK2", pdMS_TO_TICKS(40), pdMS_TO_TICKS(40), 3, 256, Job_TASK2, NULL, PTL_POLICY_USE_GLOBAL },
    };

    static PTL_GlobalConfig_t c = { PTL_POLICY_SKIP, pdTRUE, 2 };

    if (PTL_Init(&c, t, 2) == pdPASS) {
        PTL_Start();
    } else {
        UART_printf("[FATAL] PTL Init Failed!\n");
    }
    
    /* SAFETY LOOP: Should never reach here unless scheduler fails */
    for(;;) {}
    
    return 0; /* Unreachable, but keeps compiler happy */
}
